### ISSUE TITLE
this work with only view ???

### ISSUE THREAD

**Issue by jimit-ikraft** [asyafrudin/catalogue#2]
Hello,

i have some problem they work with only view ???

i means v_product change instend of product but not working with that record not getting

**Comment by asyafrudin** [comment]
Hi,

I would love to help you out, but I don't get what you mean. Can you elaborate more?

**Comment by asyafrudin** [comment]
Hi,

Can you explain more about your problem? I don't think I understand what you mean.

**Comment by jimit-ikraft** [comment]
Product controller  method 

```
public function get()
	{
		$this->load->library('datatables');
		$result = $this->datatables->getData('v_product', array('', 'code', 'description', 'price', 'category'), 'code', true);
		
		echo $result;
	}
```

"v_product"  this view record get but i want get record direct "product" table so how i can do this ??

**Comment by asyafrudin** [comment]
If you look at the `getData` function definition inside `/application/libraries/datatables.php`, you'll see that changing the source table/view can be done by changing the parameters.

Try this:

`$result = $this->datatables->getData('product', array('', 'code', 'description', 'price''), 'code', true);`

Notice how I changed both the table name (the first parameter) and the column names (the second parameter) because the column names should contain only valid column names in the related table.

**Comment by jimit-ikraft** [comment]
`DataTables warning (table id = 'products'): DataTables warning: JSON data from server could not be parsed. This is caused by a JSON formatting error.`

this error getting

**Comment by asyafrudin** [comment]
Oops, I forgot to mention that you also need to change the javascript code. Since the code above changes the number of columns retrieved from the database, you also need to modify the `/application/views/main_view.php` and the `/js/main.js` files. Follow these steps:
- In `main_view.php`, delete line 33: `<th>Category</th>`. This will remove the related column HTML markup in the view file.
- In `main.js`, delete line 31: `{ "sClass": "category", "mData": 4 },`. This will remove the related column definition in the javascript file.

**Comment by jimit-ikraft** [comment]
Thanks bro i got this :+1: 

i can make full responsive ???

**Comment by asyafrudin** [comment]
I don't think I can help you with that because the initial design of this small sample project doesn't consider responsive design.

**Comment by jimit-ikraft** [comment]
ok i got it solutions :100:
