### ISSUE TITLE
Bulk action possible this (like Delete , Copy)???

### ISSUE THREAD

**Issue by jimit-ikraft** [asyafrudin/catalogue#3]
Hello Bro,

its possible bulk action generate (Copy , Delete).

if yes so can guide me how i can make this ???

i donot need inbuilt delete , add action i want custom make 

when i used built this action so i can not dom postion change and button class can not given

**Comment by asyafrudin** [comment]
Hi,

Sorry for the late reply. It's definitely possible to add bulk action to the data table, but I can't really estimate the amount of work required to do that. You at least need to add a checkbox column that is tied to the item IDs so that you can manipulate (copy, delete, or anything at all) the items. That means changing the HTML and the javascript related to the data table. That also means modifying the server side script to handle those bulk actions. I'm not sure I can walk you through the whole technical changes though.
